// export const URL = "https://mevaroserver.kiev.ua/";
export const URL = "http://localhost:8080/";
export const CATEGORIES = "categories/";
export const ADD = "new/";
export const DELETEALL = `deleteall/`;
export const PRODUCTS = `products/`;
export const CURRENT_USD = 40;
export const ORDERS = "orders/";
export const CATEGORY = "category/";
export const UPDATE = "update/";
export const SELECT = "select/";
export const USER = "mevaro";
export const PASSWORD = "mevaro";
export const CONFIRM = "confirm/";
export const COMMENTS = `comments/`;
export const COMMENT = `comment/`;
export const PRODUCT = `product/`
export const ORDERBYMEBEL = `orderbymebel/`
